// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/calculator/calculator.proto

package com.proto.calculator;

public final class CalculatorOuterClass {
  private CalculatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_InputNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculator_InputNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_OutputNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculator_OutputNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/calculator/calculator.proto\022\ncal" +
      "culator\")\n\013InputNumber\022\014\n\004num1\030\001 \001(\005\022\014\n\004" +
      "num2\030\002 \001(\005\"\033\n\014OutputNumber\022\013\n\003num\030\001 \001(\0052" +
      "\220\002\n\nCalculator\022?\n\010Addition\022\027.calculator." +
      "InputNumber\032\030.calculator.OutputNumber\"\000\022" +
      "A\n\nSubraction\022\027.calculator.InputNumber\032\030" +
      ".calculator.OutputNumber\"\000\022?\n\010Multiply\022\027" +
      ".calculator.InputNumber\032\030.calculator.Out" +
      "putNumber\"\000\022=\n\006Divide\022\027.calculator.Input" +
      "Number\032\030.calculator.OutputNumber\"\000B\030\n\024co" +
      "m.proto.calculatorP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calculator_InputNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculator_InputNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculator_InputNumber_descriptor,
        new java.lang.String[] { "Num1", "Num2", });
    internal_static_calculator_OutputNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculator_OutputNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculator_OutputNumber_descriptor,
        new java.lang.String[] { "Num", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
