// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/calculator/calculator.proto

package com.proto.calculator;

public interface InputNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.InputNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num1 = 1;</code>
   */
  int getNum1();

  /**
   * <code>int32 num2 = 2;</code>
   */
  int getNum2();
}
