// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/calculator/calculator.proto

package com.proto.calculator;

public interface OutputNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.OutputNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1;</code>
   */
  int getNum();
}
